spring.application.name=proyectoRA9
spring.datasource.url=jdbc:mysql://localhost:13307/proyectoRA9 
spring.datasource.username=user
spring.datasource.password=user
spring.jpa.hibernate.ddl-auto=update

